<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
    <PropertyGroup>
        <Authors>Infi</Authors>
        <AssemblyName>DeathRoll</AssemblyName>
        <Version>1.5.5.0</Version>
        <Description>Plugin to help with a number of dice games. Also offers games like Tic-Tac-Toe, Minesweeper and Bahamood.</Description>
        <PackageProjectUrl>https://github.com/Infiziert90/DeathRoll</PackageProjectUrl>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputType>Library</OutputType>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="DeathRoll.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="images\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Resources\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <PropertyGroup>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NAudio.Core" Version="2.2.1" />
        <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
        <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
        <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\Sound\" />
      <Folder Include="Resources\Sprites\" />
      <Folder Include="Resources\Textures\" />
    </ItemGroup>
</Project>
